### ISSUE TITLE
Dynamic values

### ISSUE THREAD

**Issue by GMartigny** [franciscop/ola#4]
Hi,
When using Ola, it's not possible to change the values array length or object properties. It makes it a little hard to work with user inputs.
IMO, Ola should check if a value exists before [updating it](https://github.com/franciscop/ola/blob/master/ola.js#L102).

## Reproduction
```js
const values = Ola([10, 10]);
values.set([20, 20]); // Ok
values.set([30, 30, 30]); // Fail
```

**Comment by franciscop** [comment]
Yeah I don't agree, the result here is/should be undefined so please check user input before using it. You can check for `values.length` for instance before setting it:

```js
if (updatedValues.length !== values.length) {
  throw new Error('Whatever error message you want');
}
values.set(updatedValues);
```

Now we could discuss about the actual error message thrown, but this use-case would throw an error regardless since we cannot define a "default value" here. Please feel free to improve the error message in a PR if you wish.
