### ISSUE TITLE
Define duration or damping of interpolation

### ISSUE THREAD

**Issue by hatsumatsu** [franciscop/ola#5]
Thanks for his great little library!
Is there a way to set the "speed" or damping factor of the interpolation?

**Comment by franciscop** [comment]
Hi @hatsumatsu , I wrote about this but I cannot find where. With the current ola it's not possible, you can adjust the time it takes but not the damping factor. This is because I'm using a 2nd degree equation (x^2+a*x+b=0) with all degrees of freedom defined, so there's no space for any new parameter.

It was a textbook solution with as many variables as unknowns, but still it was difficult (long time since uni's algebra). So I don't dare to set it up to a [3rd degree equation](https://www.quora.com/How-can-I-solve-an-equation-of-the-third-degree) and calculate the resulting equations. IIRC you'd have to jump into the imaginary plane to solve these 3rd degree or do some other fancy maths.
